# -------- Core --------
name = "cf-template"
main = "worker/src/index.ts"
compatibility_date = "2025-08-12"        # keep current; don't drift behind

workers_dev = true

[observability.logs]
enabled = true

# -------- Bindings --------
# Durable Object(s)
[durable_objects]
bindings = [
  { name = "CHAT_SESSION", class_name = "ChatSession" }
]

# D1
[[d1_databases]]
binding = "DB"
database_name = "cf_template_db"         # replace after create
database_id = "REPLACE_ME_DB_ID"         # replace after create
migrations_dir = "./migrations"

# KV
[[kv_namespaces]]
binding = "KV_DATA"
id = "REPLACE_ME_KV_ID"                  # replace after create

# R2
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cf-template-bucket"       # replace after create

# Analytics Engine (optional but useful)
[[analytics_engine_datasets]]
binding = "ANALYTICS_DATA"
dataset = "cf_template_analytics"        # pre-create in dashboard or API

# Workers AI (only binding name is needed)
[ai]
binding = "AI"

# Queues (optional example)
# [[queues.producers]]
# binding = "Q_EVENTS"
# queue = "cf-template-events"
# [[queues.consumers]]
# queue = "cf-template-events"
# max_batch_size = 50

# -------- Vars (non-secret) --------
[vars]
default_cloudflare_model = "@cf/openai/gpt-oss-120b" #@cf/meta/llama-4-scout-17b-16e-instruct
default_cloudflare_embeddings = "@cf/baai/bge-large-en-v1.5" #@cf/baai/bge-base-en-v1.5
default_gemini_model = "gemini-2.5-flash"
default_openai_model = "gpt-4o" 
ALLOWED_ORIGINS = "http://localhost:5173,https://your-ui.hacolby.workers.dev"  # tighten later

# -------- Durable Object Migrations --------
# IMPORTANT: tags are append-only and immutable once deployed.
[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]

# Example: future rename if you ever change the class name
# [[migrations]]
# tag = "2025-08-13_rename_chatsession_to_sessionhub"
# renamed_classes = [{ from = "ChatSession", to = "SessionHub" }]

# Example: delete an old class (DANGER: wipes instances)
# [[migrations]]
# tag = "2025-08-13_delete_obsolete"
# deleted_classes = ["ObsoleteDO"]

# -------- Environments (optional) --------
[env.dev]
vars = { ENV_NAME = "dev" }
[env.prod]
vars = { ENV_NAME = "prod" }
